FROM alpine:edge
MAINTAINER Jan Broer <jan@festplatte.eu.org>

RUN apk add --no-cache ca-certificates

ADD build/rancher-gen-linux-amd64 /usr/local/bin/rancher-gen
RUN chmod +x /usr/local/bin/rancher-gen

COPY ./test /etc/rancher-gen/

ENTRYPOINT ["/usr/local/bin/rancher-gen"]
CMD ["--config", "/etc/rancher-gen/config.toml"]