#!/bin/bash

# Add binary to the release, since the docker build requires it
make build

# Get the new package version
VERSION=$(node -pe "require('./package.json').version")

# Update changelog
git changelog -t $VERSION

# Attempt to prevent race where .git/index.lock
# isn't cleared immediately
sleep 0.5

git add build History.md
